export const ArticleData = [
  {
    id: 1,
    title: "গাজা সেক্টরের মানবিক সংকট",
    image: "https://images.unsplash.com/photo-1601553562403-b18f7f0d4309",
    description:
      "গাজায় চলমান সংঘাতের কারণে সাধারণ মানুষের জীবন এবং নিরাপত্তা বিপন্ন।",
    link: "/articles/gaza-crisis",
  },
  {
    id: 2,
    title: "পালেস্টিনের শিশুদের শিক্ষা সমস্যা",
    image: "https://images.unsplash.com/photo-1598300050967-35f8a8f8fabc",
    description: "সংঘাতপূর্ণ অঞ্চলে শিশুদের শিক্ষা ও মানসিক স্বাস্থ্য বিপন্ন।",
    link: "/articles/education-issues",
  },
  {
    id: 3,
    title: "পালেস্টিনের পানির সংকট",
    image: "https://images.unsplash.com/photo-1613150291307-1f8d4d2f5f5a",
    description: "পরিষ্কার পানির অভাবে দৈনন্দিন জীবন ও স্বাস্থ্য বিপন্ন।",
    link: "/articles/water-crisis",
  },
  {
    id: 4,
    title: "ইসরায়েলি অবরোধের প্রভাব",
    image: "./images/palestine-2.jpg",
    description: "অবরোধের কারণে খাদ্য ও চিকিৎসা সরবরাহ বাধাগ্রস্ত হচ্ছে...।",
    link: "/articles/water-crisis",
  },
  {
    id: 5,
    title: "পালেস্টিনের স্বাস্থ্য সেবা চ্যালেঞ্জ",
    image: "./images/palestine-2.jpg",
    description: "দীর্ঘ সংঘাতের কারণে হাসপাতাল এবং ওষুধের অভাব...।",
    link: "/articles/water-crisis",
  },
  {
    id: 6,
    title: "পালেস্টিনের নারী অধিকার",
    image: "./images/palestine-2.jpg",
    description: "সংঘাতপূর্ণ পরিবেশে নারীর শিক্ষা ও নিরাপত্তা সংকটাপন্ন...।",
    link: "/articles/water-crisis",
  },
  {
    id: 7,
    title: "পালেস্টিনের অভিবাসী সমস্যা",
    image: "./images/palestine-2.jpg",
    description:
      "অভিবাসী শিবিরে জীবনযাপন করাটা দারিদ্র্য ও নিরাপত্তার জন্য চ্যালেঞ্জ।",
    link: "/articles/water-crisis",
  },
  {
    id: 8,
    title: "পালেস্টিনের কৃষি সংকট",
    image: "./images/palestine-2.jpg",
    description: "সংঘাতের কারণে কৃষি জমি নষ্ট হচ্ছে এবং খাদ্য উৎপাদন কমছে।",
    link: "/articles/agriculture-crisis",
  },
  {
    id: 9,
    title: "পালেস্টিনের বিদ্যুৎ সমস্যা",
    image: "https://images.unsplash.com/photo-1603616892958-1a0dcd988a5a",
    description: "বিদ্যুৎ সরবরাহ সীমিত থাকায় দৈনন্দিন জীবন জটিল হয়ে পড়ছে।",
    link: "/articles/water-crisis",
  },
  {
    id: 10,
    title: "পালেস্টিনের পরিবেশ দূষণ",
    image: "https://images.unsplash.com/photo-1596753339021-2e5f2c06e7ea",
    description:
      "দীর্ঘ সংঘাত ও অব্যবস্থাপনার কারণে পরিবেশ দূষণ ও স্বাস্থ্য ঝুঁকি বৃদ্ধি পাচ্ছে।",
    link: "/articles/environmental-issues",
  },
  {
    id: 11,
    title: "পালেস্টিনে শিশুদের নিরাপত্তা",
    image: "https://images.unsplash.com/photo-1599497166356-c8a89ff7cf9d",
    description: "সংঘাতপূর্ণ এলাকায় শিশুদের নিরাপত্তা নিশ্চিত করা কঠিন।",
    link: "/articles/child-safety",
  },
  {
    id: 12,
    title: "পালেস্টিনের সংস্কৃতি ও ঐতিহ্য",
    image: "https://images.unsplash.com/photo-1587675272737-36b3e289a5a5",
    description: "সংঘাত সত্ত্বেও প্যালেস্টিনীয় সংস্কৃতি ও ঐতিহ্য বজায় রাখা।",
    link: "/articles/culture-heritage",
  },
  {
    id: 13,
    title: "পালেস্টিনের অর্থনীতি",
    image: "https://images.unsplash.com/photo-1600195077070-fb3b2a10d6b1",
    description: "সংঘাতপূর্ণ অঞ্চলের অর্থনীতি স্থিতিশীল করা চ্যালেঞ্জিং।",
    link: "/articles/economy-challenges",
  },
  {
    id: 14,
    title: "পালেস্টিনের মানবাধিকার লঙ্ঘন",
    image: "https://images.unsplash.com/photo-1591186223892-0d5d8bdfc91f",
    description: "মানবাধিকার রক্ষার প্রচেষ্টা বিভিন্ন প্রতিবন্ধকতার সম্মুখীন।",
    link: "/articles/human-rights",
  },
  {
    id: 15,
    title: "পালেস্টিনে শান্তি প্রচেষ্টা",
    image: "https://images.unsplash.com/photo-1602233018627-0c0e9c27a9f7",
    description: "শান্তি প্রতিষ্ঠার প্রচেষ্টা এখনো কার্যকর হয়নি।",
    link: "/articles/peace-efforts",
  },
  {
    id: 16,
    title: "পালেস্টিনে আন্তর্জাতিক সহায়তা",
    image: "https://images.unsplash.com/photo-1601582588360-80e0e5b8392f",
    description: "আন্তর্জাতিক সংস্থাগুলি মানবিক সহায়তা প্রদান করছে।",
    link: "/articles/international-aid",
  },
  {
    id: 17,
    title: "পালেস্টিনে স্বাস্থ্য ও টিকা",
    image: "https://images.unsplash.com/photo-1602042944305-8c0f1b8b0f8a",
    description: "স্বাস্থ্যসেবা ও টিকা কার্যক্রম চলমান আছে সীমিতভাবে।",
    link: "/articles/health-vaccine",
  },
  {
    id: 18,
    title: "পালেস্টিনের জনসংখ্যা সমস্যা",
    image: "https://images.unsplash.com/photo-1599954585086-9ec828ee70f1",
    description: "জনসংখ্যা বৃদ্ধি এবং সীমিত সম্পদ পরিচালনা একটি বড় চ্যালেঞ্জ।",
    link: "/articles/population-issues",
  },
  {
    id: 19,
    title: "পালেস্টিনে নারী শিক্ষার গুরুত্ব",
    image: "https://images.unsplash.com/photo-1603415526960-f1c8d85f0a89",
    description: "নারী শিক্ষার উন্নয়ন সমাজের সামগ্রিক উন্নতির চাবিকাঠি।",
    link: "/articles/women-education",
  },
  {
    id: 20,
    title: "পালেস্টিনে সম্প্রদায় ভিত্তিক উদ্যোগ",
    image: "https://images.unsplash.com/photo-1601601402593-0a0d28c6a5d4",
    description:
      "স্থানীয় সম্প্রদায়গুলো একসাথে মিলিত হয়ে বিভিন্ন সমস্যার সমাধান করছে।",
    link: "/articles/community-initiatives",
  },
];
